schema_version = "1.0.0"
id = "pbsu_addon_3ds"
name = "PBSU 3D Studio (.3ds)"
version = "2.8.6"
tagline = "Import/export 3DS scenes, objects, cameras, lights & anims"
maintainer = "Arturo Cervantes Galindo"
type = "add-on"
tags = ["Import-Export", "Scene", "Object", "Camera", "Lighting", "Animation"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
website = "https://github.com/Arturo254"
copyright = [
  "© 2024 Arturo Cervantes",
  "© 2024 Arthur Dev Studio and Arturo.inc"
]

[permissions]
files = "Import and export Autodesk 3DS files"
